// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.ViewModel;

public class AdmissionCounts
{
    public Dictionary<DateTime, int> OldAge { get; set; }
    public Dictionary<DateTime, int> NursingHome { get; set; }
    public Dictionary<DateTime, int> Helpers { get; set; }
}