// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.ViewModel;

public partial class HomeNursingView
{
    public int Id { get; set; }

    public DateTime? AdmissionDate { get; set; }

    public string PatientName { get; set; }

    public string Address { get; set; }

    public int? Age { get; set; }

    public string Condition { get; set; }

    public string CustomerName { get; set; }

    public string MobileNo { get; set; }

    public string TypesofServices { get; set; }

    public decimal? RegistrationCharges { get; set; }

    public decimal? MonthlyPayment { get; set; }

    public DateTime? PeriodFrom { get; set; }

    public DateTime? PeriodTo { get; set; }

    public string IdProof { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string SUser { get; set; }

    public int? fkHelperId { get; set; }

    public string HelperName { get; set; }

    public string clientSign { get; set; }

    public string authorizedSign { get; set; }

}