// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class OldAgePaymentData
{
    public int Id { get; set; }

    public string PatientName { get; set; }

    public int? fkOldAgeId { get; set; }

    public DateTime? Date { get; set; }

    public decimal? Amount { get; set; }

    public virtual OldAge fkOldAge { get; set; }
}