// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class Attendance
{
    public int Id { get; set; }

    public int? fkHelperId { get; set; }

    public int? fkNursingId { get; set; }

    public DateTime? Date { get; set; }

    public double? Time { get; set; }

    public string Description { get; set; }

    // GPS Check-In fields
    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public double? GpsAccuracy { get; set; }

    /// <summary>Server-recorded timestamp when the employee checked in.</summary>
    public DateTime? CheckInTime { get; set; }

    /// <summary>Human-readable address from reverse geocoding.</summary>
    public string Address { get; set; }

    /// <summary>Approval status: 'Pending Approval', 'Approved', 'Rejected'.</summary>
    public string Status { get; set; }

    public virtual Helpers fkHelper { get; set; }

    public virtual HomeNursing fkNursing { get; set; }
}
