// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class Attendance
{
    public int Id { get; set; }

    public int? fkHelperId { get; set; }

    public int? fkNursingId { get; set; }

    public DateTime? Date { get; set; }

    public TimeSpan? Time { get; set; }

    public string Description { get; set; }

    public virtual Helpers fkHelper { get; set; }

    public virtual HomeNursing fkNursing { get; set; }
}