// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class Attendance
{
    public int Id { get; set; }

    public int? fkHelperId { get; set; }

    public int? fkNursingId { get; set; }

    public DateTime? Date { get; set; }

    public double? Time { get; set; }

    public string Description { get; set; }

    // ── GPS Check-In fields ──────────────────────────────────────────
    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public double? GpsAccuracy { get; set; }

    /// <summary>Server-recorded timestamp when the employee checked in.</summary>
    public DateTime? CheckInTime { get; set; }

    /// <summary>Human-readable address from reverse geocoding at check-in.</summary>
    public string Address { get; set; }

    /// <summary>Approval status: 'Pending Approval', 'Approved', 'Rejected'.</summary>
    public string Status { get; set; }

    // ── GPS Check-Out fields ─────────────────────────────────────────
    /// <summary>Server-recorded timestamp when the employee checked out.</summary>
    public DateTime? CheckOutTime { get; set; }

    public double? CheckOutLatitude { get; set; }

    public double? CheckOutLongitude { get; set; }

    public double? CheckOutGpsAccuracy { get; set; }

    /// <summary>Human-readable address from reverse geocoding at check-out.</summary>
    public string CheckOutAddress { get; set; }

    // ── Manager Approval fields ──────────────────────────────────────
    /// <summary>Calculated total working hours, set on manager approval.</summary>
    public double? TotalHours { get; set; }

    public string ManagerRemarks { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovalTimestamp { get; set; }

    // ── Navigation properties ────────────────────────────────────────
    public virtual Helpers fkHelper { get; set; }

    public virtual HomeNursing fkNursing { get; set; }
}
