// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class City
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string OfficeAddress { get; set; }

    public string MobileNumbers { get; set; }

    public string Email { get; set; }

    public string ImageBase64 { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}