// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class Helpers
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string ParentName { get; set; }

    public string MaritalStatus { get; set; }

    public string PermanentAddress { get; set; }

    public string PresentAddress { get; set; }

    public string Education { get; set; }

    public string LanguagesKnown { get; set; }

    public string Experience { get; set; }

    public string IdProof { get; set; }

    public decimal? Salary { get; set; }

    public string Reference { get; set; }

    public string FamilyMembers { get; set; }

    public virtual ICollection<Attendance> Attendance { get; set; } = new List<Attendance>();

    public virtual ICollection<HomeNursing> HomeNursing { get; set; } = new List<HomeNursing>();
}