// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class HomeNursingPayment
{
    public int Id { get; set; }

    public int? fkNursingId { get; set; }

    public DateTime? Date { get; set; }

    public decimal? Amount { get; set; }

    public virtual HomeNursing fkNursing { get; set; }
}