// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class Logger
{
    public int id { get; set; }

    public string controllerName { get; set; }

    public string actionName { get; set; }

    public string errorDescription { get; set; }

    public DateTime? createdDate { get; set; }
}