// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class OldAgeCashMemo
{
    public int id { get; set; }

    public string patientName { get; set; }

    public decimal? amount { get; set; }

    public string amountInWords { get; set; }

    public string Inpaymentof { get; set; }

    public string paymentMode { get; set; }

    public DateTime? date { get; set; }

    public string authorizedSign { get; set; }

    public string recieversSign { get; set; }
}