// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NursingHome.Db.Models;

public partial class TaskContext : DbContext
{
    public TaskContext(DbContextOptions<TaskContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Attendance> Attendance { get; set; }

    public virtual DbSet<City> City { get; set; }

    public virtual DbSet<Country> Country { get; set; }

    public virtual DbSet<Helpers> Helpers { get; set; }

    public virtual DbSet<HomeNursing> HomeNursing { get; set; }

    public virtual DbSet<HomeNursingPayment> HomeNursingPayment { get; set; }

    public virtual DbSet<OldAge> OldAge { get; set; }

    public virtual DbSet<OldAgePayment> OldAgePayment { get; set; }

    public virtual DbSet<State> State { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.Entity<Attendance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Attendan__3214EC071718A8AF");

            entity.Property(e => e.Date).HasColumnType("date");

            entity.HasOne(d => d.fkHelper).WithMany(p => p.Attendance)
                .HasForeignKey(d => d.fkHelperId)
                .HasConstraintName("FK__Attendanc__fkHel__37A5467C");

            entity.HasOne(d => d.fkNursing).WithMany(p => p.Attendance)
                .HasForeignKey(d => d.fkNursingId)
                .HasConstraintName("FK__Attendanc__fkNur__36B12243");
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__City__3214EC0770B7DB06");

            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.MobileNumbers).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Country__3214EC070530B627");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Helpers>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Helpers__3214EC077D723D46");

            entity.Property(e => e.DateOfBirth).HasColumnType("date");
            entity.Property(e => e.LanguagesKnown).HasMaxLength(100);
            entity.Property(e => e.MaritalStatus).HasMaxLength(20);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.ParentName).HasMaxLength(100);
            entity.Property(e => e.Salary).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.suser).HasMaxLength(110);
        });

        modelBuilder.Entity<HomeNursing>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__HomeNurs__3214EC0723E6127E");

            entity.Property(e => e.AdmissionDate).HasColumnType("date");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerName).HasMaxLength(100);
            entity.Property(e => e.MobileNo).HasMaxLength(20);
            entity.Property(e => e.MonthlyPayment).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PatientName).HasMaxLength(100);
            entity.Property(e => e.PaymentStatus).HasMaxLength(50);
            entity.Property(e => e.PeriodFrom).HasColumnType("date");
            entity.Property(e => e.PeriodTo).HasColumnType("date");
            entity.Property(e => e.RegistrationCharges).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SUser).HasMaxLength(50);
            entity.Property(e => e.TypesofServices).HasMaxLength(100);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.fkHelper).WithMany(p => p.HomeNursing)
                .HasForeignKey(d => d.fkHelperId)
                .HasConstraintName("FK__HomeNursi__fkHel__30F848ED");
        });

        modelBuilder.Entity<HomeNursingPayment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__HomeNurs__3214EC0771EF2C0D");

            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Date).HasColumnType("date");

            entity.HasOne(d => d.fkNursing).WithMany(p => p.HomeNursingPayment)
                .HasForeignKey(d => d.fkNursingId)
                .HasConstraintName("FK__HomeNursi__fkNur__33D4B598");
        });

        modelBuilder.Entity<OldAge>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OldAge__3214EC07242C81C6");

            entity.Property(e => e.AdmissionDate).HasColumnType("date");
            entity.Property(e => e.Condition).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerName).HasMaxLength(100);
            entity.Property(e => e.MobileNo).HasMaxLength(20);
            entity.Property(e => e.MonthlyPayment).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PatientName).HasMaxLength(100);
            entity.Property(e => e.PaymentStatus).HasMaxLength(50);
            entity.Property(e => e.PeriodFrom).HasColumnType("date");
            entity.Property(e => e.PeriodTo).HasColumnType("date");
            entity.Property(e => e.RegistrationCharges).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SUser).HasMaxLength(50);
            entity.Property(e => e.TypesofServices).HasMaxLength(100);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<OldAgePayment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OldAgePa__3214EC07CAC0EEE6");

            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Date).HasColumnType("date");

            entity.HasOne(d => d.fkOldAge).WithMany(p => p.OldAgePayment)
                .HasForeignKey(d => d.fkOldAgeId)
                .HasConstraintName("FK__OldAgePay__fkOld__2C3393D0");
        });

        modelBuilder.Entity<State>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__State__3214EC0713183885");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC077557BDBB");

            entity.HasIndex(e => e.UserName, "UQ__Users__C9F284564C103849").IsUnique();

            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.HighestQualification).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.MobileNo).HasMaxLength(20);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PinCode).HasMaxLength(20);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.fkCityNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.fkCity)
                .HasConstraintName("FK__Users__fkCity__3D5E1FD2");

            entity.HasOne(d => d.fkCountryNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.fkCountry)
                .HasConstraintName("FK__Users__HighestQu__3B75D760");

            entity.HasOne(d => d.fkStateNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.fkState)
                .HasConstraintName("FK__Users__fkState__3C69FB99");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}