// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NursingHome.Db.Models;

public partial class Users
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Roles { get; set; }

    public string MobileNo { get; set; }

    public string ImageString { get; set; }

    public string IdProof { get; set; }

    public int? fkCountry { get; set; }

    public int? fkState { get; set; }

    public int? fkCity { get; set; }

    public string PinCode { get; set; }

    public string HighestQualification { get; set; }

    public string faceDescriptor { get; set; }

    public bool IsFaceAdded { get; set; }

    public virtual City fkCityNavigation { get; set; }

    public virtual Country fkCountryNavigation { get; set; }

    public virtual State fkStateNavigation { get; set; }
}